version: "3"

services:

  servico_questionarios:
    build:
      context: ../servico_questionarios
    ports:
      - "49160:8080"
    depends_on:
      - database
      - redis

  servico_email:
    build:
      context: ../api-emails
    ports:
      - "49161:8080"

  servico_agendamento:
    build:
      context: ../servico_agendamento
    ports:
      - "49162:8080"
    depends_on:
      - database
      - redis

  gateway:
    build:
      context: ../node-authentication-gateway
    ports:
      - "49163:8080"

  servico_usuario:
    build:
      context: ../servico_usuario
    ports:
      - "49164:8080"
    depends_on:
      - database

  nginx:
    build:
      context: ../nginx
    ports:
      - "80:80"
    volumes:
      - ./techlab_app/public:/app/public
    restart: always

  database:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=techlab
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../bd/:/var/lib/postgresql/data

  database_adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
