version: "3"

services:

  servico_questionarios:
    build:
      context: ./servico_questionarios
    ports:
      - "49160:8080"
    depends_on:
      - database
      - redis

  servico_email:
    build:
      context: ./api-emails
    ports:
      - "49161:8080"

  servico_agendamento:
    build:
      context: ./servico_agendamento
    ports:
      - "49162:8080"
    depends_on:
      - database
      - redis

  servico_usuario:
    build:
      context: ./servico_usuario
    ports:
      - "49163:8080"
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=techlab
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./bd/:/var/lib/postgresql/data

  database_adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
